name: Test Custom JS action

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: run custom JS action
      uses: ./action
      id: saludo
      with:
        nombre: "Marcos"

    - name: Mostrar output de la accion
      run: echo "El mensaje de la accion es ${{steps.saludo.outputs.mensaje}}"